# Generated by Django 2.0.5 on 2018-05-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=14)),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
            ],
        ),
    ]
