# Generated by Django 2.0.5 on 2018-05-20 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0003_auto_20180520_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategy.Symbol'),
        ),
    ]
