# Generated by Django 2.0.5 on 2018-05-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0004_auto_20180520_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='min_notional',
            field=models.DecimalField(decimal_places=8, default=0.01, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symbol',
            name='min_price',
            field=models.DecimalField(decimal_places=8, default=0.01, max_digits=14),
            preserve_default=False,
        ),
    ]
