# Generated by Django 2.0.5 on 2018-05-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='side',
            field=models.CharField(choices=[('BUY', 'BUY'), ('BUY', 'BUY')], default='BUY', max_length=10),
            preserve_default=False,
        ),
    ]
