# Generated by Django 2.0.5 on 2018-05-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0007_strategy_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(help_text='交易平台返回的状态', max_length=15, null=True),
        ),
    ]
