# Generated by Django 2.0.5 on 2018-05-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0008_auto_20180522_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='side',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=10),
        ),
    ]
