# Generated by Django 2.0.5 on 2018-05-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0009_auto_20180523_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='base_price',
            field=models.DecimalField(decimal_places=8, default=1, help_text='买入时的最高价或卖出时的最低价', max_digits=14),
            preserve_default=False,
        ),
    ]
