# Generated by Django 2.0.5 on 2018-05-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0010_strategy_base_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='side',
            field=models.CharField(choices=[('buy-limit', 'buy-limit'), ('sell-limit', 'sell-limit')], max_length=10),
        ),
    ]
